#------------------------GOCASE Alpha-------------------------#
#---Zakazuje publicznego udostępniania oraz zarabianiu na ----#
#zedytowanym kodzie poniżej (równoznaczne ze -----------------# 
#-----------------------------------złamaniem praw autorskich)#
#---Zezwalam na edycje wiadomości i kodu na potrzeby własne---#
#------------------------GOCASE Alpha-------------------------#
command /case [<text>] [<text>] [<text>] [<player>]:
	permission: GOCASE.admin
	permission message: &6** &c&lNie znaleziono komendy!
	trigger:			
		if arg 1 isn't set:
			send "&6------------&5GOCASE &AADMINPANEL&6---------------" to player
			send "&6/case - &bglowna komenda"
			send "&6/case create <nazwa> [<Tu dajesz czy nie potrzebuje klucza (false)>] - &btworzysz case'a"
			send "&6/case remove <nazwa> - &busuwasz case'a"
			send "&6/case list - &blista case'ow"
			send "&6/case edit <nazwa> - &bedytujesz case'a"
			send "&6/case give <case/key> <nazwa skrzynki> <gracz> -&bdajesz skrzynke/klucz graczowi"
			send "&6/casesimulator <nazwaskrzynki> -&b symulujesz skrzynke!"				
			send "&6/casereload - &b przeladowywujesz skrypt"
			send "&6/case rare add - &c*ZBUGOWANE*&b dodaje itemek w reku do listy rzadszych (trudniej je wylosowac)"
			send "&6/case rare remove - &c*ZBUGOWANE*&b usuwa itemek w reku z listy rzadszych"
			send "&6------------&5GOCASE &AADMINPANEL&6---------------"
			stop
		if arg 1 is "create":
			if executor is console:
				send "[&6GOCASE&R] Ta komenda jest dostepna tylko w grze!" to console
				stop
			if arg 2 is set:
				if arg 3 isn't set:
					if {GOCASE::case.%uncoloured arg 2%} is set:
						send "&6**&c&lTa skrzynka juz istnieje!"
						stop
					set {GOCASE::case.%arg 2%} to uncoloured arg 2
					add {GOCASE::case.%arg 2%} to {GOCASE::cases::*}
					set {_x} to random integer between 0 and 10000
					set {_y} to 255
					set {_z} to random integer between 1 and 10000
					set {GOCASE::r.%player%} to location at {_x}, {_y}, {_z}
					set block at {GOCASE::r.%player%} to chest
					set block 1 meters east block at {GOCASE::r.%player%} to chest
					set {GOCASE::casename.%player%} to arg 2
					open the inventory of the block at {GOCASE::r.%player%} to the player
					set {GOCASE::wait.%player%} to true
				else if arg 3 is "false":
					if {GOCASE::case.%uncoloured arg 2%} is set:
						send "&6**&c&lTa skrzynka juz istnieje!"
						stop
					set {GOCASE::case.%arg 2%} to uncoloured arg 2
					set {GOASE::case.%arg 2%.key} to false
					add {GOCASE::case.%arg 2%} to {GOCASE::cases::*}
					set {_x} to random integer between 0 and 10000
					set {_y} to 255
					set {_z} to random integer between 1 and 10000
					set {GOCASE::r.%player%} to location at {_x}, {_y}, {_z}
					set block at {GOCASE::r.%player%} to chest
					set block 1 meters east block at {GOCASE::r.%player%} to chest
					set {GOCASE::casename.%player%} to arg 2
					open the inventory of the block at {GOCASE::r.%player%} to the player
					set {GOCASE::wait.%player%} to true
					stop
			else:
				send "&6**&c&lZle podane argumenty! ( Poprawnie /case create <nazwa>)"
				stop
		if arg 1 is "remove":
			if executor is not player:
				send "[&6GOCASE&R] Ta komenda jest dostepna tylko w grze!" to executor
				stop
			if arg 2 is set:
				if arg 3 isn't set:
					if {GOCASE::case.%arg 2%} is set:
						remove {GOCASE::case.%arg 2%} from {GOCASE::cases::*}
						delete {GOCASE::case.%arg 2%::*}
						delete {GOCASE::case.%arg 2%}
						send "&6**&c&l SKrzynka usunieta pomyslnie!"
						stop
					else:
						send "&6**&l&cNie ma takiej skrzynki!"
						stop
				else:
					send "&6**&c&lZle podane argumenty! ( Poprawnie /case remove <nazwa>)"
					stop
			else:
				send "&6**&c&lZle podane argumenty! ( Poprawnie /case remove <nazwa>)"
				stop
		if arg 1 is "list":
			if arg 2 is not set:
				if arg 3 is not set:
					set {_num} to 0
					open chest with 6 rows named "&6&l** &2&lLISTA SKRZYNEK" to player
					loop {GOCASE::cases::*}:							
						wait 2 ticks
						format slot {_num} of player with 1 of chest named "&5SKRZYNKA %loop-value%" to close then run "caseilist %player% %loop-value%"
						add 1 to {_num}
					stop
				else:
					send "&6**&c&lZle podane argumenty! ( Poprawnie /case list)"
					stop
			else:
				send "&6**&c&lZle podane argumenty! ( Poprawnie /case list)"
				stop
		if arg 1 is "give":
			if arg 2 is "case":
				if arg 3 is set:
					if arg 4 is set:						
						if {GOCASE::case.%arg 3%} is set:
							give chest named "&5Skrzynka %arg 3%" to arg 4
							send "&6**&c&lDano skrzynke graczowi &6&l%arg 4%&c&l!"
							stop
						else:
							send "&6**&l&cNie ma takiej skrzynki!"
							stop
					else:
						send "&6**&c&lZle podane argumenty! ( Poprawnie /case give <case/key> <nazwa skrzynki> <gracz>)"
						stop
				else:
					send "&6**&c&lZle podane argumenty! ( Poprawnie /case give <case/key> <nazwa skrzynki> <gracz>)"
					stop
			if arg 2 is "key":
				if arg 3 is set:
					if arg 4 is set:
						if {GOCASE::case.%arg 3%} is set:
							give Tripwire Hook named "&5Klucz do skrzynki %arg 3%" to arg 4
							send "&6**&c&lDano klucz graczowi &6&l%arg 4%&c&l!"
						else:
							send "&6**&l&cNie ma takiej skrzynki!"
							stop
					else:
						send "&6**&c&lZle podane argumenty! ( Poprawnie /case give <case/key> <nazwa skrzynki> <gracz>)"
						stop
				else:
					send "&6**&c&lZle podane argumenty! ( Poprawnie /case give <case/key> <nazwa skrzynki> <gracz>)"
					stop
			else:
				send "&6**&c&lZle podane argumenty! ( Poprawnie /case give <case/key> <nazwa skrzynki> <gracz>)"
				stop
		if arg 1 is "edit":
			if executor is console:
				send "[&6GOCASE&R] Ta komenda jest dostepna tylko w grze!" to console
				stop
			if arg 2 is set:
				if arg 3 is not set:
					if {GOCASE::case.%arg 2%} is set:
						set {_x} to random integer between 0 and 10000
						set {_y} to 255
						set {_z} to random integer between 1 and 10000
						set {GOCASE::r.%player%} to location at {_x}, {_y}, {_z}
						set block at {GOCASE::r.%player%} to chest
						set block 1 meters east block at {GOCASE::r.%player%} to chest
						set {GOCASE::casename.%player%} to arg 2
						loop {GOCASE::case.%arg 2%::*}:
							add loop-value to inventory of the block at {GOCASE::r.%player%}
						open the inventory of the block at {GOCASE::r.%player%} to the player
						set {GOCASE::wait.%player%} to true
						clear {GOCASE::case.%arg 2%::*}
					else:
						send "&6**&l&cNie ma takiej skrzynki!"
						stop
				else:
					send "&6**&c&lZle podane argumenty! ( Poprawnie /case edit <nazwa skrzynki> )"
					stop
			else:
				send "&6**&c&lZle podane argumenty! ( Poprawnie /case edit <nazwa skrzynki>)"
				stop
#------------------------------OSTRZEŻENIE!------------------------------------#
#UWAGA!! TO JEST BARDZO ZBUGOWANE! RAZ ZADZIALA, RAZ NIE! NIE RADZE TEGO ROBIC!#

		if arg 1 is "rare":
			if executor is console:
				send "[&6GOCASE&R] Ta komenda jest dostepna tylko w grze!" to console
				stop 
			if arg 2 is "add":
				if player's tool is not air:
					if {GOCASE::rare::*} contains player's tool:
						send "&6**&c&lTen itemek jest juz na liscie!"
						stop
					add player's tool to {GOCASE::rare::*}
					send "&6**&C&LDodano do listy!"
					stop
				else:
					send "&6**&C&LNieprawidlowy przedmiot!"
					stop
			if arg 2 is "remove":
				if player's tool is not air:
					if {GOCASE::rare::*} contains player's tool:
						remove player's tool from {GOCASE::rare::*}
						send "&6**&C&LUsunieto z listy!"
						stop
					send "&6**&C&LNa liscie nie ma takiego itemku!"
					stop
				else:
					send "&6**&C&LNieprawidlowy przedmiot!"
					stop
#------------------------------OSTRZEŻENIE!------------------------------------#

#Komenda dla graczy bez permisji#
command /caselist:
	trigger:
		open chest with 6 rows named "&6&l** &2&lLISTA SKRZYNEK" to player
		set {_num} to 0
		loop {GOCASE::cases::*}:			
			wait 2 ticks
			format slot {_num} of player with 1 of chest named "&5SKRZYNKA %loop-value%" to close then run "caseilist %player% %loop-value%"
			add 1 to {_num}
#Case simulator dostępny jest dla wszystkich#
command /casesimulator [<text>]:
	executable by: players
	trigger:
		loop {GOCASE::cases::*}:
			if arg is set:
				if {GOCASE::case.%arg%} is set:
					if loop-value is arg:
						send "&6**&c&lZa 15 sekund nastapi otwrcie, radzimy abys przeteleportowal sie w bezpieczne miejsce!"
						wait 10 seconds
						send "&6**&c&l5"
						wait 1 second
						send "&6**&c&l4"
						wait 1 second
						send "&6**&c&l3"
						wait 1 second
						send "&6**&c&l2"
						wait 1 second
						send "&6**&c&l1"
						wait 1 second
						open chest with 3 rows named "&6&l** &a&lSKRZYNKA %loop-value%" to player
						SET {GOCASE::casename.%player%} to loop-value
						SET {GOCASE::wait4.%player%} to true
						add player to {GOCASE::waits::*}
						wait 2 tick
						format slot 0 of player with 1 of Black Stained Glass Pane to close
						format slot 1 of player with 1 of Black Stained Glass Pane to close
						format slot 2 of player with 1 of Black Stained Glass Pane to close
						format slot 3 of player with 1 of Black Stained Glass Pane to close
						format slot 5 of player with 1 of Black Stained Glass Pane to close
						format slot 6 of player with 1 of Black Stained Glass Pane to close
						format slot 7 of player with 1 of Black Stained Glass Pane to close
						format slot 8 of player with 1 of Black Stained Glass Pane to close
						format slot 18 of player with 1 of Black Stained Glass Pane to close
						format slot 19 of player with 1 of Black Stained Glass Pane to close
						format slot 20 of player with 1 of Black Stained Glass Pane to close
						format slot 21 of player with 1 of Black Stained Glass Pane to close
						format slot 23 of player with 1 of Black Stained Glass Pane to close
						format slot 24 of player with 1 of Black Stained Glass Pane to close
						format slot 25 of player with 1 of Black Stained Glass Pane to close
						format slot 26 of player with 1 of Black Stained Glass Pane to close
						format slot 4 of player with 1 of Powered Rail to close
						format slot 22 of player with 1 of Powered Rail to close
						set {GOCASE::%player%.1} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 9 of player with 1 of {GOCASE::%player%.1} to close
						set {GOCASE::%player%.2} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 10 of player with 1 of {GOCASE::%player%.2} to close
						set {GOCASE::%player%.3} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 11 of player with 1 of {GOCASE::%player%.3} to close
						set {GOCASE::%player%.4} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 12 of player with 1 of {GOCASE::%player%.4} to close
						set {GOCASE::%player%.5} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 13 of player with 1 of {GOCASE::%player%.5} to close
						set {GOCASE::%player%.6} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 14 of player with 1 of {GOCASE::%player%.6} to close
						set {GOCASE::%player%.7} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 15 of player with 1 of {GOCASE::%player%.7} to close
						set {GOCASE::%player%.8} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 16 of player with 1 of {GOCASE::%player%.8} to close
						set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 17 of player with 1 of {GOCASE::%player%.9} to close
						loop 25 times:
							if loop-number is 1:
								format slot 0 of player with 1 of Purple Stained Glass Pane to close
								format slot 26 of player with 1 of Purple Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 2:
								format slot 1 of player with 1 of Purple Stained Glass Pane to close
								format slot 25 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 3:
								format slot 2 of player with 1 of Purple Stained Glass Pane to close
								format slot 24 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 4:
								format slot 3 of player with 1 of Purple Stained Glass Pane to close
								format slot 23 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 5:
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 6:
								format slot 5 of player with 1 of Purple Stained Glass Pane to close
								format slot 21 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 7:
								format slot 6 of player with 1 of Purple Stained Glass Pane to close
								format slot 20 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 8:
								format slot 7 of player with 1 of Purple Stained Glass Pane to close
								format slot 19 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 9:
								format slot 8 of player with 1 of Purple Stained Glass Pane to close
								format slot 18 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close							
							if loop-number is 10:
								format slot 7 of player with 1 of Purple Stained Glass Pane to close
								format slot 19 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 11:
								format slot 6 of player with 1 of Purple Stained Glass Pane to close
								format slot 20 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 12:
								format slot 5 of player with 1 of Purple Stained Glass Pane to close
								format slot 21 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 13:
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 14:
								format slot 3 of player with 1 of Purple Stained Glass Pane to close
								format slot 23 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 15:
								format slot 2 of player with 1 of Purple Stained Glass Pane to close
								format slot 24 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 16:
								format slot 1 of player with 1 of Purple Stained Glass Pane to close
								format slot 25 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 17:
								format slot 0 of player with 1 of Purple Stained Glass Pane to close
								format slot 26 of player with 1 of Purple Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 18:
								format slot 1 of player with 1 of Purple Stained Glass Pane to close
								format slot 25 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 19:
								format slot 2 of player with 1 of Purple Stained Glass Pane to close
								format slot 24 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 20:
								format slot 3 of player with 1 of Purple Stained Glass Pane to close
								format slot 23 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 21:
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 22:
								format slot 5 of player with 1 of Purple Stained Glass Pane to close
								format slot 21 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 23:
								format slot 6 of player with 1 of Purple Stained Glass Pane to close
								format slot 20 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 24:
								format slot 7 of player with 1 of Purple Stained Glass Pane to close
								format slot 19 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 25:
								format slot 8 of player with 1 of Purple Stained Glass Pane to close
								format slot 18 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
							set {GOCASE::%player%.1} to {GOCASE::%player%.2}
							format slot 9 of player with 1 of {GOCASE::%player%.1} to close
							set {GOCASE::%player%.2} to {GOCASE::%player%.3}
							format slot 10 of player with 1 of {GOCASE::%player%.2} to close
							set {GOCASE::%player%.3} to {GOCASE::%player%.4}
							format slot 11 of player with 1 of {GOCASE::%player%.3} to close
							set {GOCASE::%player%.4} to {GOCASE::%player%.5}
							format slot 12 of player with 1 of {GOCASE::%player%.4} to close
							set {GOCASE::%player%.5} to {GOCASE::%player%.6}
							format slot 13 of player with 1 of {GOCASE::%player%.5} to close
							set {GOCASE::%player%.6} to {GOCASE::%player%.7}
							format slot 14 of player with 1 of {GOCASE::%player%.6} to close
							set {GOCASE::%player%.7} to {GOCASE::%player%.8}
							format slot 15 of player with 1 of {GOCASE::%player%.7} to close
							set {GOCASE::%player%.8} to {GOCASE::%player%.9}
							format slot 16 of player with 1 of {GOCASE::%player%.8} to close
							set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
							if chance of 90%:
								if {GOCASE::rare::*} contains {GOCASE::%player%.9}:
									set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 17 of player with 1 of {GOCASE::%player%.9} to close
							if loop-number-2 is smaller than 20:
								play raw sound "random.pop" at player with pitch 1.5 volume 1
								wait 0.3 second
							else if loop-number-2 is not higher than 24:
								play raw sound "random.pop" at player with pitch 1.5 volume 1
								wait 1 second
							else:
								play raw sound "random.pop" at player with pitch 1.5 volume 1
								wait 1.5 second
						play raw sound "mob.endermen.portal" at player with pitch 0.001 volume 1
						delete {GOCASE::wait4.%player%}
						close player's inventory
						delete {GOCASE::%player%.1}
						delete {GOCASE::%player%.2}
						delete {GOCASE::%player%.3}
						delete {GOCASE::%player%.4}
						delete {GOCASE::%player%.5}
						delete {GOCASE::%player%.6}
						delete {GOCASE::%player%.7}
						delete {GOCASE::%player%.8}
						delete {GOCASE::%player%.9}
						delete {GOCASE::casename.%player%}					
						stop
				else:
					send "&6**&c&lNie ma takiej skrzynki!"
					stop
			else:
				send "&6**&c&lPodaj nazwe skrzynki!"
				stop 					
#Komenda dla graczy
command /caseinf:
	trigger:
		send "&6------------&5GOCASE&6---------------" to player
		send "&6**&c&lLista komend:"
		send "&6/caselist - &blista case'ow"
		send "&6/casesimulator <nazwa skrzynki> -&b symulujesz dana skrzynke!"				
		send "&6------------&5GOCASEL&6---------------"
		stop 
#Wyswietlanie listy przedmiotow w skrzynce#
command /caseilist <player> <text>:
	executable by: console
	trigger:
		wait 2 ticks
		set {_num} to 0
		open chest with 6 rows named "LISTA ITEMKOW" to arg 1
		set {_pl} to arg 1
		wait 2 ticks
		loop {GOCASE::case.%uncoloured arg 2%::*}:			
			format slot {_num} of {_pl} with 1 of loop-value to close
			add 1 to {_num}
#Komenda na reload skryptu, taka dupna trochę, ale...#
command /casereload:
	permission: gocase.admin
	trigger:
		console command "sk reload gocase"
#Komenda pomagajaca zrobienie itemku np. Battle Scarred#
command /damagei <number>:
	trigger:
		if player has permission "damage.i":
			if executor is player:
				if player's tool is not air:
					damage player's tool by arg
				ELSE:
					send "&cNieprawidlowy przedmiot!"
					stop
			else:
				send "[&6GOCASE&R]Ta komenda moze byc wykonywana tylko w grze!"		
#Zmiana nazwy itemku#
command /itemrename [<text>]:
	permission: item.rename
	trigger:
		if command executor is console:
			send "[&6GOCASE&R]Ta komenda moze byc wykonywana tylko w grze!" to executor
			stop
		if arg 1 is set:
			if player's tool is not air:
				set name of player's tool to coloured arg 1
				send "&6**&c&lNazwa itemku zmieniona!"
				stop		
			else:
				send "&6**&c&lNieprawidlowy przedmiot!"
				stop
		else:
			send "&6**&c&lPodaj nowa nazwe przedmiotu!"
			stop 
#Zmiana opisu itemku#
command /itemlore [<text>]:
	permission: item.rename
	trigger:
		if command executor is console:
			send "[&6GOCASE&R]Ta komenda moze byc wykonywana tylko w grze!" to executor
			stop
		if arg 1 is set:
			if player's tool is not air:
				set lore of player's tool to coloured arg 1					
				send "&6**&c&lOpis itemku zmieniona!"
				stop		
			else:
				send "&6**&c&lNieprawidlowy przedmiot!"
				stop
		else:
			send "&6**&c&lPodaj nowy opis przedmiotu!"
			stop				
on load:
	send "[&6GOCASE&r] Laduje..." to console
	send "[&6GOCASE&r] Skrypt gotowy do uzycia! Enjoy! //febbe" to console
	broadcast "&6**&c&lSkrypt na skrzynki zostal przeladowany!"
on unload:
	send "[&6GOCASE&r] Wylaczam..." to console
	send "[&6GOCASE&r] Dziekuje za korzystanie! //febbe" to console
	broadcast "&6**&c&lSkrypt na skrzynki zostal wylaczony!"
on inventory close:
	if {GOCASE::wait.%player%} is true:
		loop all items in inventory of the block at {GOCASE::r.%player%}:
			if loop-item is not air:
				add loop-item to {GOCASE::case.%{GOCASE::casename.%player%}%::*}
		send "&6** &C&LSkrzynka %{GOCASE::casename.%player%}% zostala utworzona/zedytowana!"
		delete {GOCASE::wait.%player%}
		delete {GOCASE::casename.%player%}
		set block at {GOCASE::r.%player%} to air
		set block 1 meters east block at {GOCASE::r.%player%} to air
		delete {GOCASE::r.%player%}		
		stop
	if {GOCASE::wait4.%player%} is true:
		wait 2 ticks
		open chest with 3 rows named "&6&l** &a&lSKRZYNKA %{GOCASE::casename.%player%}%" to player
		format slot 0 of player with 1 of Black Stained Glass Pane to close
		format slot 1 of player with 1 of Black Stained Glass Pane to close
		format slot 2 of player with 1 of Black Stained Glass Pane to close
		format slot 3 of player with 1 of Black Stained Glass Pane to close
		format slot 5 of player with 1 of Black Stained Glass Pane to close
		format slot 6 of player with 1 of Black Stained Glass Pane to close
		format slot 7 of player with 1 of Black Stained Glass Pane to close
		format slot 8 of player with 1 of Black Stained Glass Pane to close
		format slot 18 of player with 1 of Black Stained Glass Pane to close
		format slot 19 of player with 1 of Black Stained Glass Pane to close
		format slot 20 of player with 1 of Black Stained Glass Pane to close
		format slot 21 of player with 1 of Black Stained Glass Pane to close
		format slot 23 of player with 1 of Black Stained Glass Pane to close
		format slot 24 of player with 1 of Black Stained Glass Pane to close
		format slot 25 of player with 1 of Black Stained Glass Pane to close
		format slot 26 of player with 1 of Black Stained Glass Pane to close
		format slot 4 of player with 1 of Powered Rail to close
		format slot 22 of player with 1 of Powered Rail to close
		stop
on rightclick:
	loop {GOCASE::cases::*}:
		if name of player's tool is "&5Skrzynka %loop-value%" or "&5Klucz do skrzynki %loop-value%":
			cancel event
			if name of player's tool is "&5Skrzynka %loop-value%" or "&5Klucz do skrzynki %loop-value%":
				cancel event
				if name of player's tool is "&5Skrzynka %loop-value%":
					if {GOASE::case.%loop-value%.key} is false:						
						remove chest named "&5Skrzynka %loop-value%" from player's tool
						send "&6**&c&l Za 15 sekund nastapi otwarcie, radzimy abys przeteleportowal sie w bezpieczne miejsce!"
						wait 10 seconds
						send "&6**&c&l5"
						wait 1 second
						send "&6**&c&l4"
						wait 1 second
						send "&6**&c&l3"
						wait 1 second
						send "&6**&c&l2"
						wait 1 second
						send "&6**&c&l1"
						wait 1 second
						broadcast "&6**&c&lGracz &5&l%player%&c&l, otworzyl skrzynke %loop-value%"
						open chest with 3 rows named "&6&l** &a&lSKRZYNKA %loop-value%" to player
						SET {GOCASE::casename.%player%} to loop-value
						SET {GOCASE::wait4.%player%} to true
						wait 2 tick
						format slot 0 of player with 1 of Black Stained Glass Pane to close
						format slot 1 of player with 1 of Black Stained Glass Pane to close
						format slot 2 of player with 1 of Black Stained Glass Pane to close
						format slot 3 of player with 1 of Black Stained Glass Pane to close
						format slot 5 of player with 1 of Black Stained Glass Pane to close
						format slot 6 of player with 1 of Black Stained Glass Pane to close
						format slot 7 of player with 1 of Black Stained Glass Pane to close
						format slot 8 of player with 1 of Black Stained Glass Pane to close
						format slot 18 of player with 1 of Black Stained Glass Pane to close
						format slot 19 of player with 1 of Black Stained Glass Pane to close
						format slot 20 of player with 1 of Black Stained Glass Pane to close
						format slot 21 of player with 1 of Black Stained Glass Pane to close
						format slot 23 of player with 1 of Black Stained Glass Pane to close
						format slot 24 of player with 1 of Black Stained Glass Pane to close
						format slot 25 of player with 1 of Black Stained Glass Pane to close
						format slot 26 of player with 1 of Black Stained Glass Pane to close
						format slot 4 of player with 1 of Powered Rail to close
						format slot 22 of player with 1 of Powered Rail to close
						set {GOCASE::%player%.1} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 9 of player with 1 of {GOCASE::%player%.1} to close
						set {GOCASE::%player%.2} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 10 of player with 1 of {GOCASE::%player%.2} to close
						set {GOCASE::%player%.3} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 11 of player with 1 of {GOCASE::%player%.3} to close
						set {GOCASE::%player%.4} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 12 of player with 1 of {GOCASE::%player%.4} to close
						set {GOCASE::%player%.5} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 13 of player with 1 of {GOCASE::%player%.5} to close
						set {GOCASE::%player%.6} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 14 of player with 1 of {GOCASE::%player%.6} to close
						set {GOCASE::%player%.7} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 15 of player with 1 of {GOCASE::%player%.7} to close
						set {GOCASE::%player%.8} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 16 of player with 1 of {GOCASE::%player%.8} to close
						set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
						format slot 17 of player with 1 of {GOCASE::%player%.9} to close
						loop 25 times:
							if loop-number is 1:
								format slot 0 of player with 1 of Purple Stained Glass Pane to close
								format slot 26 of player with 1 of Purple Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 2:
								format slot 1 of player with 1 of Purple Stained Glass Pane to close
								format slot 25 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 3:
								format slot 2 of player with 1 of Purple Stained Glass Pane to close
								format slot 24 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 4:
								format slot 3 of player with 1 of Purple Stained Glass Pane to close
								format slot 23 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 5:
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 6:
								format slot 5 of player with 1 of Purple Stained Glass Pane to close
								format slot 21 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 7:
								format slot 6 of player with 1 of Purple Stained Glass Pane to close
								format slot 20 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 8:
								format slot 7 of player with 1 of Purple Stained Glass Pane to close
								format slot 19 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 9:
								format slot 8 of player with 1 of Purple Stained Glass Pane to close
								format slot 18 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close							
							if loop-number is 10:
								format slot 7 of player with 1 of Purple Stained Glass Pane to close
								format slot 19 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 11:
								format slot 6 of player with 1 of Purple Stained Glass Pane to close
								format slot 20 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 12:
								format slot 5 of player with 1 of Purple Stained Glass Pane to close
								format slot 21 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 13:
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 14:
								format slot 3 of player with 1 of Purple Stained Glass Pane to close
								format slot 23 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 15:
								format slot 2 of player with 1 of Purple Stained Glass Pane to close
								format slot 24 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 16:
								format slot 1 of player with 1 of Purple Stained Glass Pane to close
								format slot 25 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 17:
								format slot 0 of player with 1 of Purple Stained Glass Pane to close
								format slot 26 of player with 1 of Purple Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 18:
								format slot 1 of player with 1 of Purple Stained Glass Pane to close
								format slot 25 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 19:
								format slot 2 of player with 1 of Purple Stained Glass Pane to close
								format slot 24 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 20:
								format slot 3 of player with 1 of Purple Stained Glass Pane to close
								format slot 23 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 21:
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 22:
								format slot 5 of player with 1 of Purple Stained Glass Pane to close
								format slot 21 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 23:
								format slot 6 of player with 1 of Purple Stained Glass Pane to close
								format slot 20 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 24:
								format slot 7 of player with 1 of Purple Stained Glass Pane to close
								format slot 19 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 8 of player with 1 of Black Stained Glass Pane to close
								format slot 18 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
							if loop-number is 25:
								format slot 8 of player with 1 of Purple Stained Glass Pane to close
								format slot 18 of player with 1 of Purple Stained Glass Pane to close
								format slot 0 of player with 1 of Black Stained Glass Pane to close
								format slot 1 of player with 1 of Black Stained Glass Pane to close
								format slot 2 of player with 1 of Black Stained Glass Pane to close
								format slot 3 of player with 1 of Black Stained Glass Pane to close
								format slot 5 of player with 1 of Black Stained Glass Pane to close
								format slot 6 of player with 1 of Black Stained Glass Pane to close
								format slot 7 of player with 1 of Black Stained Glass Pane to close
								format slot 26 of player with 1 of Black Stained Glass Pane to close
								format slot 19 of player with 1 of Black Stained Glass Pane to close
								format slot 20 of player with 1 of Black Stained Glass Pane to close
								format slot 21 of player with 1 of Black Stained Glass Pane to close
								format slot 23 of player with 1 of Black Stained Glass Pane to close
								format slot 24 of player with 1 of Black Stained Glass Pane to close
								format slot 25 of player with 1 of Black Stained Glass Pane to close
							set {GOCASE::%player%.1} to {GOCASE::%player%.2}
							format slot 9 of player with 1 of {GOCASE::%player%.1} to close
							set {GOCASE::%player%.2} to {GOCASE::%player%.3}
							format slot 10 of player with 1 of {GOCASE::%player%.2} to close
							set {GOCASE::%player%.3} to {GOCASE::%player%.4}
							format slot 11 of player with 1 of {GOCASE::%player%.3} to close
							set {GOCASE::%player%.4} to {GOCASE::%player%.5}
							format slot 12 of player with 1 of {GOCASE::%player%.4} to close
							set {GOCASE::%player%.5} to {GOCASE::%player%.6}
							format slot 13 of player with 1 of {GOCASE::%player%.5} to close
							set {GOCASE::%player%.6} to {GOCASE::%player%.7}
							format slot 14 of player with 1 of {GOCASE::%player%.6} to close
							set {GOCASE::%player%.7} to {GOCASE::%player%.8}
							format slot 15 of player with 1 of {GOCASE::%player%.7} to close
							set {GOCASE::%player%.8} to {GOCASE::%player%.9}
							format slot 16 of player with 1 of {GOCASE::%player%.8} to close
							set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
							#100% - 90% = 10%   - szansa na wypadniecie rzadkiego itemku#
							if chance of 90%:
								if {GOCASE::rare::*} contains {GOCASE::%player%.9}:
									set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 17 of player with 1 of {GOCASE::%player%.9} to close
							if loop-number-2 is smaller than 20:
								play raw sound "random.pop" at player with pitch 1.5 volume 1
								wait 0.3 second
							else if loop-number-2 is not higher than 24:
								play raw sound "random.pop" at player with pitch 1.5 volume 1
								wait 1 second
							else:
								play raw sound "random.pop" at player with pitch 1.5 volume 1
								wait 1.5 second
						play raw sound "mob.endermen.portal" at player with pitch 0.001 volume 1
						delete {GOCASE::wait4.%player%}
						close player's inventory
						if player can hold {GOCASE::%player%.5}:
							give player {GOCASE::%player%.5}
						else:
							drop {GOCASE::%player%.5}
							send "&6**&lPrzedmiot zostal upuszczony na ziemie!"
						send "&6**&c&lGratulacje, sprawdz co wygrales!"					
						delete {GOCASE::wait4.%player%}
						close player's inventory
						delete {GOCASE::%player%.1}
						delete {GOCASE::%player%.2}
						delete {GOCASE::%player%.3}
						delete {GOCASE::%player%.4}
						delete {GOCASE::%player%.5}
						delete {GOCASE::%player%.6}
						delete {GOCASE::%player%.7}
						delete {GOCASE::%player%.8}
						delete {GOCASE::%player%.9}
						delete {GOCASE::casename.%player%}
					else:
						if player has Tripwire Hook named "&5Klucz do skrzynki %loop-value%":
							remove Tripwire Hook named "&5Klucz do skrzynki %loop-value%" from player
							remove chest named "&5Skrzynka %loop-value%" from player
							send "&6**&c&l Klucz do twojej skrzynki pasuje, za 15 sekund nastapi jej otwrcie, radzimy abys przeteleportowal sie w bezpieczne miejsce!"
							wait 10 seconds
							send "&6**&c&l5"
							wait 1 second
							send "&6**&c&l4"
							wait 1 second
							send "&6**&c&l3"
							wait 1 second
							send "&6**&c&l2"
							wait 1 second
							send "&6**&c&l1"
							wait 1 second
							broadcast "&6**&c&lGracz &5&l%player%&c&l, otworzyl skrzynke %loop-value%"
							open chest with 3 rows named "&6&l** &a&lSKRZYNKA %loop-value%" to player
							SET {GOCASE::casename.%player%} to loop-value
							SET {GOCASE::wait4.%player%} to true
							add player to {GOCASE::waits::*}
							wait 2 tick
							format slot 0 of player with 1 of Black Stained Glass Pane to close
							format slot 1 of player with 1 of Black Stained Glass Pane to close
							format slot 2 of player with 1 of Black Stained Glass Pane to close
							format slot 3 of player with 1 of Black Stained Glass Pane to close
							format slot 5 of player with 1 of Black Stained Glass Pane to close
							format slot 6 of player with 1 of Black Stained Glass Pane to close
							format slot 7 of player with 1 of Black Stained Glass Pane to close
							format slot 8 of player with 1 of Black Stained Glass Pane to close
							format slot 18 of player with 1 of Black Stained Glass Pane to close
							format slot 19 of player with 1 of Black Stained Glass Pane to close
							format slot 20 of player with 1 of Black Stained Glass Pane to close
							format slot 21 of player with 1 of Black Stained Glass Pane to close
							format slot 23 of player with 1 of Black Stained Glass Pane to close
							format slot 24 of player with 1 of Black Stained Glass Pane to close
							format slot 25 of player with 1 of Black Stained Glass Pane to close
							format slot 26 of player with 1 of Black Stained Glass Pane to close
							format slot 4 of player with 1 of Powered Rail to close
							format slot 22 of player with 1 of Powered Rail to close
							set {GOCASE::%player%.1} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 9 of player with 1 of {GOCASE::%player%.1} to close
							set {GOCASE::%player%.2} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 10 of player with 1 of {GOCASE::%player%.2} to close
							set {GOCASE::%player%.3} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 11 of player with 1 of {GOCASE::%player%.3} to close
							set {GOCASE::%player%.4} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 12 of player with 1 of {GOCASE::%player%.4} to close
							set {GOCASE::%player%.5} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 13 of player with 1 of {GOCASE::%player%.5} to close
							set {GOCASE::%player%.6} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 14 of player with 1 of {GOCASE::%player%.6} to close
							set {GOCASE::%player%.7} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 15 of player with 1 of {GOCASE::%player%.7} to close
							set {GOCASE::%player%.8} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 16 of player with 1 of {GOCASE::%player%.8} to close
							set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
							format slot 17 of player with 1 of {GOCASE::%player%.9} to close
							loop 25 times:
								if loop-number is 1:
									format slot 0 of player with 1 of Purple Stained Glass Pane to close
									format slot 26 of player with 1 of Purple Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 2:
									format slot 1 of player with 1 of Purple Stained Glass Pane to close
									format slot 25 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 3:
									format slot 2 of player with 1 of Purple Stained Glass Pane to close
									format slot 24 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 4:
									format slot 3 of player with 1 of Purple Stained Glass Pane to close
									format slot 23 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 5:
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 6:
									format slot 5 of player with 1 of Purple Stained Glass Pane to close
									format slot 21 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 7:
									format slot 6 of player with 1 of Purple Stained Glass Pane to close
									format slot 20 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 8:
									format slot 7 of player with 1 of Purple Stained Glass Pane to close
									format slot 19 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 9:
									format slot 8 of player with 1 of Purple Stained Glass Pane to close
									format slot 18 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close							
								if loop-number is 10:
									format slot 7 of player with 1 of Purple Stained Glass Pane to close
									format slot 19 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 11:
									format slot 6 of player with 1 of Purple Stained Glass Pane to close
									format slot 20 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 12:
									format slot 5 of player with 1 of Purple Stained Glass Pane to close
									format slot 21 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 13:
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 14:
									format slot 3 of player with 1 of Purple Stained Glass Pane to close
									format slot 23 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 15:
									format slot 2 of player with 1 of Purple Stained Glass Pane to close
									format slot 24 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 16:
									format slot 1 of player with 1 of Purple Stained Glass Pane to close
									format slot 25 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 17:
									format slot 0 of player with 1 of Purple Stained Glass Pane to close
									format slot 26 of player with 1 of Purple Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 18:
									format slot 1 of player with 1 of Purple Stained Glass Pane to close
									format slot 25 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 19:
									format slot 2 of player with 1 of Purple Stained Glass Pane to close
									format slot 24 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 20:
									format slot 3 of player with 1 of Purple Stained Glass Pane to close
									format slot 23 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 21:
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 22:
									format slot 5 of player with 1 of Purple Stained Glass Pane to close
									format slot 21 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 23:
									format slot 6 of player with 1 of Purple Stained Glass Pane to close
									format slot 20 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 24:
									format slot 7 of player with 1 of Purple Stained Glass Pane to close
									format slot 19 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 8 of player with 1 of Black Stained Glass Pane to close
									format slot 18 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
								if loop-number is 25:
									format slot 8 of player with 1 of Purple Stained Glass Pane to close
									format slot 18 of player with 1 of Purple Stained Glass Pane to close
									format slot 0 of player with 1 of Black Stained Glass Pane to close
									format slot 1 of player with 1 of Black Stained Glass Pane to close
									format slot 2 of player with 1 of Black Stained Glass Pane to close
									format slot 3 of player with 1 of Black Stained Glass Pane to close
									format slot 5 of player with 1 of Black Stained Glass Pane to close
									format slot 6 of player with 1 of Black Stained Glass Pane to close
									format slot 7 of player with 1 of Black Stained Glass Pane to close
									format slot 26 of player with 1 of Black Stained Glass Pane to close
									format slot 19 of player with 1 of Black Stained Glass Pane to close
									format slot 20 of player with 1 of Black Stained Glass Pane to close
									format slot 21 of player with 1 of Black Stained Glass Pane to close
									format slot 23 of player with 1 of Black Stained Glass Pane to close
									format slot 24 of player with 1 of Black Stained Glass Pane to close
									format slot 25 of player with 1 of Black Stained Glass Pane to close
								set {GOCASE::%player%.1} to {GOCASE::%player%.2}
								format slot 9 of player with 1 of {GOCASE::%player%.1} to close
								set {GOCASE::%player%.2} to {GOCASE::%player%.3}
								format slot 10 of player with 1 of {GOCASE::%player%.2} to close
								set {GOCASE::%player%.3} to {GOCASE::%player%.4}
								format slot 11 of player with 1 of {GOCASE::%player%.3} to close
								set {GOCASE::%player%.4} to {GOCASE::%player%.5}
								format slot 12 of player with 1 of {GOCASE::%player%.4} to close
								set {GOCASE::%player%.5} to {GOCASE::%player%.6}
								format slot 13 of player with 1 of {GOCASE::%player%.5} to close
								set {GOCASE::%player%.6} to {GOCASE::%player%.7}
								format slot 14 of player with 1 of {GOCASE::%player%.6} to close
								set {GOCASE::%player%.7} to {GOCASE::%player%.8}
								format slot 15 of player with 1 of {GOCASE::%player%.7} to close
								set {GOCASE::%player%.8} to {GOCASE::%player%.9}
								format slot 16 of player with 1 of {GOCASE::%player%.8} to close
								set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
								if chance of 90%:
									if {GOCASE::rare::*} contains {GOCASE::%player%.9}:
										set {GOCASE::%player%.9} to random element out of {GOCASE::case.%loop-value%::*}
								format slot 17 of player with 1 of {GOCASE::%player%.9} to close
								if loop-number-2 is smaller than 20:
									play raw sound "random.pop" at player with pitch 1.5 volume 1
									wait 0.3 second
								else if loop-number-2 is not higher than 24:
									play raw sound "random.pop" at player with pitch 1.5 volume 1
									wait 1 second
								else:
									play raw sound "random.pop" at player with pitch 1.5 volume 1
									wait 1.5 second
							play raw sound "mob.endermen.portal" at player with pitch 0.001 volume 1
							delete {GOCASE::wait4.%player%}
							close player's inventory
							if player can hold {GOCASE::%player%.5}:
								give player {GOCASE::%player%.5}
							else:
								drop {GOCASE::%player%.5}
								send "&6**&lPrzedmiot zostal upuszczony na ziemie!"
							send "&6**&c&lGratulacje, sprawdz co wygrales!"					
							delete {GOCASE::wait4.%player%}
							close player's inventory
							delete {GOCASE::%player%.1}
							delete {GOCASE::%player%.2}
							delete {GOCASE::%player%.3}
							delete {GOCASE::%player%.4}
							delete {GOCASE::%player%.5}
							delete {GOCASE::%player%.6}
							delete {GOCASE::%player%.7}
							delete {GOCASE::%player%.8}
							delete {GOCASE::%player%.9}
							delete {GOCASE::casename.%player%}
							REMOVE player from {GOCASE::waits::*}
						else:
							send "&6**&c&lNie masz klucza do tej skrzynki!"
							stop
#Zabezpieczenie przed konfliktami na serwerze#
on join:
	delete {GOCASE::wait4.%player%}
	delete {GOCASE::wait.%player%}
#Drop#
#Szanse mozesz odpowiednio modyfikowac#
on mine stone:
	loop {GOCASE::cases::*}:
		if chance of 1%:
			if player can hold chest:
				give player chest named "&5Skrzynka %loop-value%"
				send "&5%player% , &c&lznalazles skrzynke &6%loop-value%&c! &cZnajdz, badz kup  klucz i otworz skrzynke aby wolosowac nagrode!" to player 
				stop
			else:
				give player chest named "&5Skrzynka %loop-value%"
				send "&5%player% , &c&lznalazles skrzynke &6%loop-value%&c! &cZnajdz, badz kup  klucz i otworz skrzynke aby wolosowac nagrode!" to player  
				send "&6** &cPrzedmiot zostal upuszczony na ziemie, z powodu braku miejsca w ekwipunku!"
				stop
		if chance of 1%:
			if player can hold Tripwire Hook:
				give player Tripwire Hook named "&5Klucz do skrzynki %loop-value%"
				send "&5%player% , &c&lznalazles klucz do skrzynki &6%loop-value%&c! &cZnajdz, badz kup  odpowiednia skrzynke i otworz ja aby wolosowac nagrode!" to player  
				stop
			else:
				give player Tripwire Hook named "&5Klucz do skrzynki %loop-value%"
				send "&5%player% , &c&lznalazles klucz do skrzynki &6%loop-value%&c! &cZnajdz, badz kup  odpowiednia skrzynke i otworz ja aby wolosowac nagrode!" to player 
				send "&6** &cPrzedmiot zostal upuszczony na ziemie, z powodu braku miejsca w ekwipunku!"
				stop
